---
sudo: required
language: bash
dist: xenial
services:
  - docker

script:
  - cd package
  - docker build -t yast-test-image -f Dockerfile .
  - docker run -it --privileged --rm yast-test-image rake -r yast/rake -V
  - docker run -it --privileged --rm -e TERM=xterm yast-test-image yast2 proxy summary
  - docker run -it --privileged --rm yast-test-image shellcheck /usr/local/bin/yast-travis-ruby
